# Generated by Django 5.1.4 on 2025-01-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='udated_time',
            new_name='updated_time',
        ),
    ]
