# Generated by Django 5.1.4 on 2025-04-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
